# Generated by Django 5.2.8 on 2025-11-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('circuit_ref', models.SlugField(primary_key=True, serialize=False, verbose_name='ID трассы (slug)')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на Wiki')),
            ],
            options={
                'verbose_name': 'Трасса',
                'verbose_name_plural': 'Трассы',
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('constructor_ref', models.SlugField(primary_key=True, serialize=False, verbose_name='ID команды (slug)')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('nationality', models.CharField(max_length=100, verbose_name='Национальность')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на Wiki')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_ref', models.SlugField(primary_key=True, serialize=False, verbose_name='ID пилота (slug)')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Код (VER)')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('forename', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(max_length=100, verbose_name='Национальность')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на Wiki')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='Фото')),
                ('biography', models.TextField(blank=True, help_text='Текст на русском', verbose_name='Биография (RU)')),
            ],
            options={
                'verbose_name': 'Пилот',
                'verbose_name_plural': 'Пилоты',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Сезон (Год)')),
                ('round', models.IntegerField(verbose_name='Этап')),
                ('name', models.CharField(max_length=200, verbose_name='Название Гран-при')),
                ('date', models.DateField(verbose_name='Дата гонки')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на Wiki')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.circuit', verbose_name='Трасса')),
            ],
            options={
                'verbose_name': 'Гонка',
                'verbose_name_plural': 'Гонки',
                'ordering': ['-year', 'round'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.IntegerField(verbose_name='Старт')),
                ('position', models.IntegerField(null=True, verbose_name='Финиш (место)')),
                ('position_text', models.CharField(help_text='R для схода', max_length=10, verbose_name='Финиш (текст)')),
                ('points', models.FloatField(verbose_name='Очки')),
                ('status', models.CharField(help_text='Finished, Collision...', max_length=100, verbose_name='Статус')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.constructor', verbose_name='Команда')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='racing.driver', verbose_name='Пилот')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='racing.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
