# Generated by Django 5.2.8 on 2025-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='championships',
            field=models.IntegerField(default=0, verbose_name='Титулов Чемпиона Мира'),
        ),
    ]
