# Generated by Django 5.2.8 on 2025-11-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_driver_championships'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.IntegerField(verbose_name='Старт')),
                ('position', models.IntegerField(null=True, verbose_name='Финиш (место)')),
                ('position_text', models.CharField(help_text='R для схода', max_length=10, verbose_name='Финиш (текст)')),
                ('points', models.FloatField(verbose_name='Очки')),
                ('status', models.CharField(help_text='Finished, Collision...', max_length=100, verbose_name='Статус')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.constructor', verbose_name='Команда')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to='racing.driver', verbose_name='Пилот')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to='racing.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Результат Спринта',
                'verbose_name_plural': 'Результаты Спринтов',
            },
        ),
    ]
