# Generated by Django 5.2.8 on 2025-11-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0003_sprintresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание/История'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная команда (текущий сезон)'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='constructors/', verbose_name='Логотип'),
        ),
    ]
