# Generated by Django 5.2.8 on 2025-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0004_constructor_description_constructor_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='championships',
            field=models.IntegerField(default=0, verbose_name='Кубков Конструкторов'),
        ),
    ]
