# Generated by Django 5.2.8 on 2025-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0005_constructor_championships'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='circuits/', verbose_name='Схема трассы'),
        ),
    ]
