# Generated by Django 5.2.8 on 2025-11-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0006_circuit_layout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='hex_color',
            field=models.CharField(default='#333333', help_text='Например: #FF0000', max_length=7, verbose_name='Цвет (HEX)'),
        ),
    ]
