# Generated by Django 5.2.8 on 2025-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0007_constructor_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='fp1_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Практика 1'),
        ),
        migrations.AddField(
            model_name='race',
            name='fp2_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Практика 2'),
        ),
        migrations.AddField(
            model_name='race',
            name='fp3_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Практика 3'),
        ),
        migrations.AddField(
            model_name='race',
            name='qualifying_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Квалификация'),
        ),
        migrations.AddField(
            model_name='race',
            name='race_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время старта гонки'),
        ),
        migrations.AddField(
            model_name='race',
            name='sprint_quali_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Спринт-квалификация'),
        ),
    ]
