# Generated by Django 5.2.8 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0008_race_fp1_time_race_fp2_time_race_fp3_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo_cutout',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/cutouts/', verbose_name='Фото (Вырезка/Подиум)'),
        ),
    ]
